version: '3.3'
    #docker run -d -p 9000:9000 --name portainer --restart=always -v "/var/run/docker.sock:/var/run/docker.sock" portainer/por
services:
                   
    worker_nodezqm:
        image: node_zmq
        container_name: worker_nodezqm
        entrypoint: node worker.js
        networks:
            test:
                ipv4_address: '10.1.0.100'

    producer_nodezqm:
        image: node_zmq
        container_name: producer_nodezqm
        entrypoint: node producer.js
        networks:
            test:
                ipv4_address: '10.1.0.101'

networks:
  test:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24                